[theme]
primaryColor = "#0077B6"  # a bright blue-green color
backgroundColor = "#212121"  # a dark gray background
secondaryBackgroundColor = "#333333"  # a darker gray secondary background
textColor = "#FFFFFF"  # white text color
font = "sans serif"